name: Installation Check
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  install-check:
    name: Secure Install Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout PR branch with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full history for accurate diffing
      - name: Add upstream remote and fetch base branch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream master
      - name: Detect fork
        id: forkcheck
        run: |
          if [ "${{ github.repository }}" != "${{ github.event.pull_request.head.repo.full_name }}" ]; then
            echo "is_fork=true" >> $GITHUB_OUTPUT
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
          fi
      - name: Check if install scripts were modified
        id: filecheck
        run: |
          MODIFIED=$(git diff --name-only upstream/master HEAD)
          echo "$MODIFIED"
          if echo "$MODIFIED" | grep -qE '^install-atomicredteam\.ps1$|^install-atomicsfolder\.ps1$'; then
            echo "scripts_modified=true" >> $GITHUB_OUTPUT
          else
            echo "scripts_modified=false" >> $GITHUB_OUTPUT
          fi
      - name: Decide whether to run scripts
        id: safecheck
        run: |
          if [ "${{ steps.filecheck.outputs.scripts_modified }}" = "false" ]; then
            echo "safe=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.forkcheck.outputs.is_fork }}" = "false" ]; then
            echo "safe=true" >> $GITHUB_OUTPUT
          else
            echo "safe=false" >> $GITHUB_OUTPUT
          fi
      - name: Execute install scripts
        if: steps.safecheck.outputs.safe == 'true'
        shell: pwsh
        run: |
          Write-Output "Running install scripts from trusted context"
          ./install-atomicredteam.ps1
          ./install-atomicsfolder.ps1
      - name: Skip script execution
        if: steps.safecheck.outputs.safe != 'true'
        run: |
          echo "::warning:: install scripts were modified in a forked PR. Skipping execution until merge."
